language: java
before_install: ant init-ivy
install: 
  - ant build
  - ant dependencytree

jdk:
  - oraclejdk11
  - openjdk11
  
script:
  - echo "skipping tests"
  
after_success:
- bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)
